services:
  frontend:
    build: ./frontend
    image: dashboard-frontend:latest
    ports:
      - "80:80"
    networks:
      - dashboard
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build: ./backend
    image: dashboard-backend:latest
    ports:
      - "3000:3000"
    networks:
      - dashboard
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    restart: unless-stopped

  redis:
    image: redis:8.2.2
    volumes:
      - redis:/data
    networks:
      - dashboard
    restart: unless-stopped

volumes:
  redis:

networks:
  dashboard: